"""empty message

Revision ID: 1c08355d5088
Revises: 11e629d3cf98
Create Date: 2024-03-28 13:05:22.026261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1208355d5088'
down_revision = '11e629d3cf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_APIKey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AK_intro', sa.String(length=600), nullable=True))
        batch_op.alter_column('AK_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('AK_value',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('AK_auth')
        batch_op.drop_column('AK_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_APIKey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AK_type', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('AK_auth', sa.VARCHAR(length=30), nullable=True))
        batch_op.alter_column('AK_value',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('AK_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('AK_intro')

    # ### end Alembic commands ###
