"""empty message

Revision ID: 12b13ec55320
Revises: 11de45dc7b38
Create Date: 2024-01-24 15:09:40.156372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b13ec55320'
down_revision = '11de45dc7b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_TestProjectUser',
    sa.Column('tPU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TPid', sa.String(length=30), nullable=True),
    sa.Column('uid', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['TPid'], ['tb_TestProject.tP_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['tb_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tPU_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_TestProjectUser')
    # ### end Alembic commands ###
