"""empty message

Revision ID: 940427fe1718
Revises: 61deffa27b6f
Create Date: 2023-12-13 15:17:01.674327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940427fe1718'
down_revision = '61deffa27b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_DataSet',
    sa.Column('DS_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DS_name', sa.String(length=30), nullable=True),
    sa.Column('DS_info', sa.String(length=200), nullable=True),
    sa.Column('DS_url', sa.String(length=80), nullable=True),
    sa.Column('userid', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('DS_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_DataSet')
    # ### end Alembic commands ###
