"""empty message

Revision ID: 1f56df0ec528
Revises: df499f3796cb
Create Date: 2023-12-22 13:15:09.564974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef56df0ec528'
down_revision = 'df499f3796cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_TestProject',
    sa.Column('tP_id', sa.String(length=30), nullable=False),
    sa.Column('tP_name', sa.String(length=30), nullable=True),
    sa.Column('tP_time', sa.DateTime(), nullable=True),
    sa.Column('tP_status', sa.Integer(), nullable=True),
    sa.Column('tP_progress', sa.Float(), nullable=True),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('AK1', sa.String(length=30), nullable=True),
    sa.Column('AK2', sa.String(length=30), nullable=True),
    sa.Column('DS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AK1'], ['tb_APIKey.apiKey_id'], ),
    sa.ForeignKeyConstraint(['AK2'], ['tb_APIKey.apiKey_id'], ),
    sa.ForeignKeyConstraint(['DS'], ['tb_DataSet.DS_id'], ),
    sa.ForeignKeyConstraint(['Pid'], ['tb_Project.project_id'], ),
    sa.PrimaryKeyConstraint('tP_id')
    )
    op.create_table('tb_QA',
    sa.Column('QA_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('QA_time', sa.DateTime(), nullable=True),
    sa.Column('QA_question', sa.String(length=80), nullable=True),
    sa.Column('QA_answer', sa.String(length=200), nullable=True),
    sa.Column('QA_score', sa.Float(), nullable=True),
    sa.Column('QA_thread', sa.Integer(), nullable=True),
    sa.Column('TPid', sa.String(length=30), nullable=True),
    sa.Column('uid', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['TPid'], ['tb_TestProject.tP_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['tb_user.user_id'], ),
    sa.PrimaryKeyConstraint('QA_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_QA')
    op.drop_table('tb_TestProject')
    # ### end Alembic commands ###
