"""empty message

Revision ID: 7246b0ae8fb1
Revises: ef56df0ec528
Create Date: 2023-12-27 11:09:14.996034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eg46b0ae8fb1'
down_revision = 'ef56df0ec528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_QA', schema=None) as batch_op:
        batch_op.add_column(sa.Column('QA_field', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_QA', schema=None) as batch_op:
        batch_op.drop_column('QA_field')

    # ### end Alembic commands ###
