"""empty message

Revision ID: f2486197ea25
Revises: f194af1e719c
Create Date: 2024-01-22 15:14:14.102477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2486197ea25'
down_revision = 'f194af1e719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_ProjectAPIKey',
    sa.Column('Project_APIKey_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('AKid', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['AKid'], ['tb_APIKey.apiKey_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Pid'], ['tb_Project.project_id'], ),
    sa.PrimaryKeyConstraint('Project_APIKey_id')
    )
    op.create_table('tb_ProjectDataSet',
    sa.Column('Project_DataSet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('DSid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DSid'], ['tb_DataSet.DS_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Pid'], ['tb_Project.project_id'], ),
    sa.PrimaryKeyConstraint('Project_DataSet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_ProjectDataSet')
    op.drop_table('tb_ProjectAPIKey')
    # ### end Alembic commands ###
